blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.all_blogs, name='all_blogs'),
    path('<int:blog_id>/', views.detail, name='detail'),
]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from portfolio import views


urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

class Blog(models.Model):
    title = models.CharField(max_length = 100)
    date = models.DateField()
    description = models.TextField(max_length = 15000)

    def __str__(self):
        return self.title

portfolio/models.py
from django.db import models

class Project(models.Model):
    title = models.TextField(max_length = 100)
    description = models.CharField(max_length = 250)
    image = models.ImageField(upload_to="portfolio/images/")
    url = models.URLField(blank = True)

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog

def all_blogs(request):
    blogs = Blog.objects.order_by('-date')[:5]
    return render (request, 'blog/all_blogs.html', {'blogs': blogs})

def detail (request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    return render (request, 'blog/detail.html', {'blog': blog})

personal_portfolio/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'home')

portfolio/views.py
from django.shortcuts import render
from .models import Project

def home(request):
    projects = Project.objects.all()
    return render(request, 'portfolio/index.html', {'projects': projects})

blog/templates/blog/all_blogs.html
{% extends 'portfolio/base.html' %}

{% block content %}

{% load blog.rupluralize %}

</html>
  <head><h1 align="center"><font color="red">Это голова</font></h1></head>
  <title>Мой первый блог</title>

  <body>
    <h1>Хеллоу, ёптыдь!)</h1>
    <h2>Я написал {{ blogs.count }} {{ blogs.count|rupluralize:"блог-пост, блог-поста, блог-постов" }}</h2>
    <br>
    <h2>Начинаем заполнять мой первый блог</h2>

  {% for blog in blogs %}
      <a href="{% url 'blog:detail' blog.id %}"><h1>{{ blog.title }}</h1></a>
      {{ blog.date|date:'d M Y'|upper }}
      <h3>{{ blog.description|striptags|truncatechars:150 }}</h3><br><br>
  {% endfor %}

  </body>

{% endblock %}
</html>

blog/templates/blog/detail.html
{% extends 'portfolio/base.html' %}

{% block content %}

<h1>{{ blog.title }}</h1><br>
<h2>-- {{ blog.date|date:'d F Y' }} --</h2><br>
{{ blog.description|safe }}

{% endblock %}

portfolio/templates/portfolio/base.html
{% load static %}

<!doctype html>
<html lang="ru">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <link rel="icon" type="image/png" href="{% static "portfolio/111.png" %}">

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Мой поиск</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Домашняя страница</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Описание</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

      {% block content %}{% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>

</html>

portfolio/templates/portfolio/index.html
{% extends 'portfolio/base.html' %}

{% block content %}

{% load static %}


  <head><title>)))Это описание страницы</title></head>

  <body>

    <a href="{% url 'blog:all_blogs' %}">Страничка блога</a>
    <h2>Это первая страничка в этом проекте!!!</h2>

    <img src="{% static 'portfolio/DSC_0236.JPG' %}" height="350">
    <p><a href="{% static 'portfolio/blank_resume_2019_blanki-vsem.ru_.pdf' %}">Резюме</a></p>


    {% for project in projects %}

            {{ project.title }}<br>
            {{ project.description }}<br>
            <img src="{{ project.image.url }}" height="280"><br>
            {% if project.url %}
            <a href="{{ project.url }}">Ссылка</a><br><br>
            {% endif %}

    {% endfor %}
    </table>

  </body>
{% endblock %}
</html>